// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: ClientDatanodeProtocol.proto

package hadoop_hdfs

import (
	hadoop_common "github.com/zhanglistar/hdfs/internal/protocol/hadoop_common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//*
// block - block for which visible length is requested
type GetReplicaVisibleLengthRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Block *ExtendedBlockProto `protobuf:"bytes,1,req,name=block" json:"block,omitempty"`
}

func (x *GetReplicaVisibleLengthRequestProto) Reset() {
	*x = GetReplicaVisibleLengthRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientDatanodeProtocol_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReplicaVisibleLengthRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplicaVisibleLengthRequestProto) ProtoMessage() {}

func (x *GetReplicaVisibleLengthRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_ClientDatanodeProtocol_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplicaVisibleLengthRequestProto.ProtoReflect.Descriptor instead.
func (*GetReplicaVisibleLengthRequestProto) Descriptor() ([]byte, []int) {
	return file_ClientDatanodeProtocol_proto_rawDescGZIP(), []int{0}
}

func (x *GetReplicaVisibleLengthRequestProto) GetBlock() *ExtendedBlockProto {
	if x != nil {
		return x.Block
	}
	return nil
}

//*
// length - visible length of the block
type GetReplicaVisibleLengthResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Length *uint64 `protobuf:"varint,1,req,name=length" json:"length,omitempty"`
}

func (x *GetReplicaVisibleLengthResponseProto) Reset() {
	*x = GetReplicaVisibleLengthResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientDatanodeProtocol_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReplicaVisibleLengthResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplicaVisibleLengthResponseProto) ProtoMessage() {}

func (x *GetReplicaVisibleLengthResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_ClientDatanodeProtocol_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplicaVisibleLengthResponseProto.ProtoReflect.Descriptor instead.
func (*GetReplicaVisibleLengthResponseProto) Descriptor() ([]byte, []int) {
	return file_ClientDatanodeProtocol_proto_rawDescGZIP(), []int{1}
}

func (x *GetReplicaVisibleLengthResponseProto) GetLength() uint64 {
	if x != nil && x.Length != nil {
		return *x.Length
	}
	return 0
}

//*
// void request
type RefreshNamenodesRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshNamenodesRequestProto) Reset() {
	*x = RefreshNamenodesRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientDatanodeProtocol_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshNamenodesRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshNamenodesRequestProto) ProtoMessage() {}

func (x *RefreshNamenodesRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_ClientDatanodeProtocol_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshNamenodesRequestProto.ProtoReflect.Descriptor instead.
func (*RefreshNamenodesRequestProto) Descriptor() ([]byte, []int) {
	return file_ClientDatanodeProtocol_proto_rawDescGZIP(), []int{2}
}

//*
// void response
type RefreshNamenodesResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RefreshNamenodesResponseProto) Reset() {
	*x = RefreshNamenodesResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientDatanodeProtocol_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshNamenodesResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshNamenodesResponseProto) ProtoMessage() {}

func (x *RefreshNamenodesResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_ClientDatanodeProtocol_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshNamenodesResponseProto.ProtoReflect.Descriptor instead.
func (*RefreshNamenodesResponseProto) Descriptor() ([]byte, []int) {
	return file_ClientDatanodeProtocol_proto_rawDescGZIP(), []int{3}
}

//*
// blockPool - block pool to be deleted
// force - if false, delete the block pool only if it is empty.
//         if true, delete the block pool even if it has blocks.
type DeleteBlockPoolRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockPool *string `protobuf:"bytes,1,req,name=blockPool" json:"blockPool,omitempty"`
	Force     *bool   `protobuf:"varint,2,req,name=force" json:"force,omitempty"`
}

func (x *DeleteBlockPoolRequestProto) Reset() {
	*x = DeleteBlockPoolRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientDatanodeProtocol_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBlockPoolRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlockPoolRequestProto) ProtoMessage() {}

func (x *DeleteBlockPoolRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_ClientDatanodeProtocol_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlockPoolRequestProto.ProtoReflect.Descriptor instead.
func (*DeleteBlockPoolRequestProto) Descriptor() ([]byte, []int) {
	return file_ClientDatanodeProtocol_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteBlockPoolRequestProto) GetBlockPool() string {
	if x != nil && x.BlockPool != nil {
		return *x.BlockPool
	}
	return ""
}

func (x *DeleteBlockPoolRequestProto) GetForce() bool {
	if x != nil && x.Force != nil {
		return *x.Force
	}
	return false
}

//*
// void response
type DeleteBlockPoolResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteBlockPoolResponseProto) Reset() {
	*x = DeleteBlockPoolResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientDatanodeProtocol_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBlockPoolResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlockPoolResponseProto) ProtoMessage() {}

func (x *DeleteBlockPoolResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_ClientDatanodeProtocol_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlockPoolResponseProto.ProtoReflect.Descriptor instead.
func (*DeleteBlockPoolResponseProto) Descriptor() ([]byte, []int) {
	return file_ClientDatanodeProtocol_proto_rawDescGZIP(), []int{5}
}

//*
// Gets the file information where block and its metadata is stored
// block - block for which path information is being requested
// token - block token
//
// This message is deprecated in favor of file descriptor passing.
type GetBlockLocalPathInfoRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Block *ExtendedBlockProto       `protobuf:"bytes,1,req,name=block" json:"block,omitempty"`
	Token *hadoop_common.TokenProto `protobuf:"bytes,2,req,name=token" json:"token,omitempty"`
}

func (x *GetBlockLocalPathInfoRequestProto) Reset() {
	*x = GetBlockLocalPathInfoRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientDatanodeProtocol_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlockLocalPathInfoRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockLocalPathInfoRequestProto) ProtoMessage() {}

func (x *GetBlockLocalPathInfoRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_ClientDatanodeProtocol_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockLocalPathInfoRequestProto.ProtoReflect.Descriptor instead.
func (*GetBlockLocalPathInfoRequestProto) Descriptor() ([]byte, []int) {
	return file_ClientDatanodeProtocol_proto_rawDescGZIP(), []int{6}
}

func (x *GetBlockLocalPathInfoRequestProto) GetBlock() *ExtendedBlockProto {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *GetBlockLocalPathInfoRequestProto) GetToken() *hadoop_common.TokenProto {
	if x != nil {
		return x.Token
	}
	return nil
}

//*
// block - block for which file path information is being returned
// localPath - file path where the block data is stored
// localMetaPath - file path where the block meta data is stored
//
// This message is deprecated in favor of file descriptor passing.
type GetBlockLocalPathInfoResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Block         *ExtendedBlockProto `protobuf:"bytes,1,req,name=block" json:"block,omitempty"`
	LocalPath     *string             `protobuf:"bytes,2,req,name=localPath" json:"localPath,omitempty"`
	LocalMetaPath *string             `protobuf:"bytes,3,req,name=localMetaPath" json:"localMetaPath,omitempty"`
}

func (x *GetBlockLocalPathInfoResponseProto) Reset() {
	*x = GetBlockLocalPathInfoResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientDatanodeProtocol_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlockLocalPathInfoResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockLocalPathInfoResponseProto) ProtoMessage() {}

func (x *GetBlockLocalPathInfoResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_ClientDatanodeProtocol_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockLocalPathInfoResponseProto.ProtoReflect.Descriptor instead.
func (*GetBlockLocalPathInfoResponseProto) Descriptor() ([]byte, []int) {
	return file_ClientDatanodeProtocol_proto_rawDescGZIP(), []int{7}
}

func (x *GetBlockLocalPathInfoResponseProto) GetBlock() *ExtendedBlockProto {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *GetBlockLocalPathInfoResponseProto) GetLocalPath() string {
	if x != nil && x.LocalPath != nil {
		return *x.LocalPath
	}
	return ""
}

func (x *GetBlockLocalPathInfoResponseProto) GetLocalMetaPath() string {
	if x != nil && x.LocalMetaPath != nil {
		return *x.LocalMetaPath
	}
	return ""
}

//*
// forUpgrade - if true, clients are advised to wait for restart and quick
//              upgrade restart is instrumented. Otherwise, datanode does
//              the regular shutdown.
type ShutdownDatanodeRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ForUpgrade *bool `protobuf:"varint,1,req,name=forUpgrade" json:"forUpgrade,omitempty"`
}

func (x *ShutdownDatanodeRequestProto) Reset() {
	*x = ShutdownDatanodeRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientDatanodeProtocol_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShutdownDatanodeRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownDatanodeRequestProto) ProtoMessage() {}

func (x *ShutdownDatanodeRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_ClientDatanodeProtocol_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownDatanodeRequestProto.ProtoReflect.Descriptor instead.
func (*ShutdownDatanodeRequestProto) Descriptor() ([]byte, []int) {
	return file_ClientDatanodeProtocol_proto_rawDescGZIP(), []int{8}
}

func (x *ShutdownDatanodeRequestProto) GetForUpgrade() bool {
	if x != nil && x.ForUpgrade != nil {
		return *x.ForUpgrade
	}
	return false
}

type ShutdownDatanodeResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ShutdownDatanodeResponseProto) Reset() {
	*x = ShutdownDatanodeResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientDatanodeProtocol_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShutdownDatanodeResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownDatanodeResponseProto) ProtoMessage() {}

func (x *ShutdownDatanodeResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_ClientDatanodeProtocol_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownDatanodeResponseProto.ProtoReflect.Descriptor instead.
func (*ShutdownDatanodeResponseProto) Descriptor() ([]byte, []int) {
	return file_ClientDatanodeProtocol_proto_rawDescGZIP(), []int{9}
}

//* Tell datanode to evict active clients that are writing
type EvictWritersRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EvictWritersRequestProto) Reset() {
	*x = EvictWritersRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientDatanodeProtocol_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvictWritersRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvictWritersRequestProto) ProtoMessage() {}

func (x *EvictWritersRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_ClientDatanodeProtocol_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvictWritersRequestProto.ProtoReflect.Descriptor instead.
func (*EvictWritersRequestProto) Descriptor() ([]byte, []int) {
	return file_ClientDatanodeProtocol_proto_rawDescGZIP(), []int{10}
}

type EvictWritersResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EvictWritersResponseProto) Reset() {
	*x = EvictWritersResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientDatanodeProtocol_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvictWritersResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvictWritersResponseProto) ProtoMessage() {}

func (x *EvictWritersResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_ClientDatanodeProtocol_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvictWritersResponseProto.ProtoReflect.Descriptor instead.
func (*EvictWritersResponseProto) Descriptor() ([]byte, []int) {
	return file_ClientDatanodeProtocol_proto_rawDescGZIP(), []int{11}
}

//*
// Ping datanode for liveness and quick info
type GetDatanodeInfoRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetDatanodeInfoRequestProto) Reset() {
	*x = GetDatanodeInfoRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientDatanodeProtocol_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDatanodeInfoRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatanodeInfoRequestProto) ProtoMessage() {}

func (x *GetDatanodeInfoRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_ClientDatanodeProtocol_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatanodeInfoRequestProto.ProtoReflect.Descriptor instead.
func (*GetDatanodeInfoRequestProto) Descriptor() ([]byte, []int) {
	return file_ClientDatanodeProtocol_proto_rawDescGZIP(), []int{12}
}

type GetDatanodeInfoResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LocalInfo *DatanodeLocalInfoProto `protobuf:"bytes,1,req,name=localInfo" json:"localInfo,omitempty"`
}

func (x *GetDatanodeInfoResponseProto) Reset() {
	*x = GetDatanodeInfoResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientDatanodeProtocol_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDatanodeInfoResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatanodeInfoResponseProto) ProtoMessage() {}

func (x *GetDatanodeInfoResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_ClientDatanodeProtocol_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatanodeInfoResponseProto.ProtoReflect.Descriptor instead.
func (*GetDatanodeInfoResponseProto) Descriptor() ([]byte, []int) {
	return file_ClientDatanodeProtocol_proto_rawDescGZIP(), []int{13}
}

func (x *GetDatanodeInfoResponseProto) GetLocalInfo() *DatanodeLocalInfoProto {
	if x != nil {
		return x.LocalInfo
	}
	return nil
}

type TriggerBlockReportRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Incremental *bool `protobuf:"varint,1,req,name=incremental" json:"incremental,omitempty"`
}

func (x *TriggerBlockReportRequestProto) Reset() {
	*x = TriggerBlockReportRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientDatanodeProtocol_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TriggerBlockReportRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerBlockReportRequestProto) ProtoMessage() {}

func (x *TriggerBlockReportRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_ClientDatanodeProtocol_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerBlockReportRequestProto.ProtoReflect.Descriptor instead.
func (*TriggerBlockReportRequestProto) Descriptor() ([]byte, []int) {
	return file_ClientDatanodeProtocol_proto_rawDescGZIP(), []int{14}
}

func (x *TriggerBlockReportRequestProto) GetIncremental() bool {
	if x != nil && x.Incremental != nil {
		return *x.Incremental
	}
	return false
}

type TriggerBlockReportResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TriggerBlockReportResponseProto) Reset() {
	*x = TriggerBlockReportResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientDatanodeProtocol_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TriggerBlockReportResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerBlockReportResponseProto) ProtoMessage() {}

func (x *TriggerBlockReportResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_ClientDatanodeProtocol_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerBlockReportResponseProto.ProtoReflect.Descriptor instead.
func (*TriggerBlockReportResponseProto) Descriptor() ([]byte, []int) {
	return file_ClientDatanodeProtocol_proto_rawDescGZIP(), []int{15}
}

type GetBalancerBandwidthRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetBalancerBandwidthRequestProto) Reset() {
	*x = GetBalancerBandwidthRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientDatanodeProtocol_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBalancerBandwidthRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalancerBandwidthRequestProto) ProtoMessage() {}

func (x *GetBalancerBandwidthRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_ClientDatanodeProtocol_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalancerBandwidthRequestProto.ProtoReflect.Descriptor instead.
func (*GetBalancerBandwidthRequestProto) Descriptor() ([]byte, []int) {
	return file_ClientDatanodeProtocol_proto_rawDescGZIP(), []int{16}
}

//*
// bandwidth - balancer bandwidth value of the datanode.
type GetBalancerBandwidthResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bandwidth *uint64 `protobuf:"varint,1,req,name=bandwidth" json:"bandwidth,omitempty"`
}

func (x *GetBalancerBandwidthResponseProto) Reset() {
	*x = GetBalancerBandwidthResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientDatanodeProtocol_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBalancerBandwidthResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalancerBandwidthResponseProto) ProtoMessage() {}

func (x *GetBalancerBandwidthResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_ClientDatanodeProtocol_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalancerBandwidthResponseProto.ProtoReflect.Descriptor instead.
func (*GetBalancerBandwidthResponseProto) Descriptor() ([]byte, []int) {
	return file_ClientDatanodeProtocol_proto_rawDescGZIP(), []int{17}
}

func (x *GetBalancerBandwidthResponseProto) GetBandwidth() uint64 {
	if x != nil && x.Bandwidth != nil {
		return *x.Bandwidth
	}
	return 0
}

var File_ClientDatanodeProtocol_proto protoreflect.FileDescriptor

var file_ClientDatanodeProtocol_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b,
	0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x64, 0x66, 0x73, 0x1a, 0x0e, 0x53, 0x65, 0x63,
	0x75, 0x72, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x68, 0x64, 0x66,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x55, 0x0a, 0x23, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x56, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x4c, 0x65, 0x6e, 0x67, 0x74,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2e, 0x0a,
	0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x68,
	0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x64, 0x66, 0x73, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x6e,
	0x64, 0x65, 0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x36, 0x0a,
	0x24, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x56, 0x69, 0x73, 0x69, 0x62,
	0x6c, 0x65, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x04, 0x22, 0x1e, 0x0a, 0x1c, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68,
	0x4e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1f, 0x0a, 0x1d, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68,
	0x4e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3f, 0x0a, 0x1b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x6f,
	0x6f, 0x6c, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x12, 0x0d, 0x0a, 0x05, 0x66, 0x6f, 0x72, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x08, 0x22, 0x1e, 0x0a, 0x1c, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7d, 0x0a, 0x21, 0x47, 0x65, 0x74, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2e, 0x0a, 0x05,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x68, 0x61,
	0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x64, 0x66, 0x73, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64,
	0x65, 0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x28, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x68, 0x61,
	0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7e, 0x0a, 0x22, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2e, 0x0a, 0x05,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x68, 0x61,
	0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x64, 0x66, 0x73, 0x2e, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64,
	0x65, 0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x0a, 0x09,
	0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x12,
	0x15, 0x0a, 0x0d, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x4d, 0x65, 0x74, 0x61, 0x50, 0x61, 0x74, 0x68,
	0x18, 0x03, 0x20, 0x02, 0x28, 0x09, 0x22, 0x32, 0x0a, 0x1c, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f,
	0x77, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x0a, 0x66, 0x6f, 0x72, 0x55, 0x70, 0x67,
	0x72, 0x61, 0x64, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x08, 0x22, 0x1f, 0x0a, 0x1d, 0x53, 0x68,
	0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1a, 0x0a, 0x18, 0x45,
	0x76, 0x69, 0x63, 0x74, 0x57, 0x72, 0x69, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1b, 0x0a, 0x19, 0x45, 0x76, 0x69, 0x63, 0x74,
	0x57, 0x72, 0x69, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1d, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x6e,
	0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x56, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x6e, 0x6f,
	0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x36, 0x0a, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e,
	0x68, 0x64, 0x66, 0x73, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65, 0x4c, 0x6f, 0x63,
	0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x35, 0x0a, 0x1e, 0x54,
	0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x0a,
	0x0b, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x08, 0x22, 0x21, 0x0a, 0x1f, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x22, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x72, 0x42, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x36, 0x0a, 0x21, 0x47, 0x65, 0x74,
	0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x42, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11,
	0x0a, 0x09, 0x62, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x04, 0x32, 0x91, 0x0b, 0x0a, 0x1d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x6e, 0x6f, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x7e, 0x0a, 0x17, 0x67, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x56, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x30,
	0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x64, 0x66, 0x73, 0x2e, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x56, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x4c, 0x65,
	0x6e, 0x67, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x31, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x64, 0x66, 0x73, 0x2e, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x56, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65,
	0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x69, 0x0a, 0x10, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x4e, 0x61,
	0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x29, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70,
	0x2e, 0x68, 0x64, 0x66, 0x73, 0x2e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x4e, 0x61, 0x6d,
	0x65, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x2a, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x64, 0x66, 0x73,
	0x2e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x4e, 0x61, 0x6d, 0x65, 0x6e, 0x6f, 0x64, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x66,
	0x0a, 0x0f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x6f, 0x6f,
	0x6c, 0x12, 0x28, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x64, 0x66, 0x73, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x6f, 0x6f, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x29, 0x2e, 0x68, 0x61,
	0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x64, 0x66, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x78, 0x0a, 0x15, 0x67, 0x65, 0x74, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x2e, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x64, 0x66, 0x73, 0x2e, 0x47, 0x65,
	0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x2f, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x64, 0x66, 0x73, 0x2e, 0x47, 0x65,
	0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x69, 0x0a, 0x10, 0x73, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x44, 0x61, 0x74, 0x61,
	0x6e, 0x6f, 0x64, 0x65, 0x12, 0x29, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x64,
	0x66, 0x73, 0x2e, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x6e,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x2a, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x64, 0x66, 0x73, 0x2e, 0x53, 0x68,
	0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x5d, 0x0a, 0x0c, 0x65,
	0x76, 0x69, 0x63, 0x74, 0x57, 0x72, 0x69, 0x74, 0x65, 0x72, 0x73, 0x12, 0x25, 0x2e, 0x68, 0x61,
	0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x64, 0x66, 0x73, 0x2e, 0x45, 0x76, 0x69, 0x63, 0x74, 0x57,
	0x72, 0x69, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x26, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x64, 0x66, 0x73,
	0x2e, 0x45, 0x76, 0x69, 0x63, 0x74, 0x57, 0x72, 0x69, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x66, 0x0a, 0x0f, 0x67, 0x65,
	0x74, 0x44, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x28, 0x2e,
	0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x64, 0x66, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x44,
	0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x29, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70,
	0x2e, 0x68, 0x64, 0x66, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x81, 0x01, 0x0a, 0x18, 0x67, 0x65, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x31, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x64, 0x66, 0x73, 0x2e, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x32, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x64, 0x66, 0x73,
	0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x75, 0x0a, 0x14, 0x73, 0x74, 0x61, 0x72, 0x74, 0x52,
	0x65, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2d,
	0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x64, 0x66, 0x73, 0x2e, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2e, 0x2e,
	0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x64, 0x66, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x8d, 0x01,
	0x0a, 0x1c, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x61, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x12, 0x35,
	0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x64, 0x66, 0x73, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x50,
	0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x36, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68,
	0x64, 0x66, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x6f, 0x0a,
	0x12, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x12, 0x2b, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x64, 0x66,
	0x73, 0x2e, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x2c, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x64, 0x66, 0x73, 0x2e, 0x54,
	0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x75,
	0x0a, 0x14, 0x67, 0x65, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x42, 0x61, 0x6e,
	0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x2d, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e,
	0x68, 0x64, 0x66, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72,
	0x42, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2e, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68,
	0x64, 0x66, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x42,
	0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x86, 0x01, 0x0a, 0x25, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x70,
	0x61, 0x63, 0x68, 0x65, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x64, 0x66, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x42,
	0x1c, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x5a, 0x39, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x68, 0x61, 0x6e, 0x67, 0x6c,
	0x69, 0x73, 0x74, 0x61, 0x72, 0x2f, 0x68, 0x64, 0x66, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x68, 0x61, 0x64,
	0x6f, 0x6f, 0x70, 0x5f, 0x68, 0x64, 0x66, 0x73, 0x88, 0x01, 0x01, 0xa0, 0x01, 0x01,
}

var (
	file_ClientDatanodeProtocol_proto_rawDescOnce sync.Once
	file_ClientDatanodeProtocol_proto_rawDescData = file_ClientDatanodeProtocol_proto_rawDesc
)

func file_ClientDatanodeProtocol_proto_rawDescGZIP() []byte {
	file_ClientDatanodeProtocol_proto_rawDescOnce.Do(func() {
		file_ClientDatanodeProtocol_proto_rawDescData = protoimpl.X.CompressGZIP(file_ClientDatanodeProtocol_proto_rawDescData)
	})
	return file_ClientDatanodeProtocol_proto_rawDescData
}

var file_ClientDatanodeProtocol_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_ClientDatanodeProtocol_proto_goTypes = []interface{}{
	(*GetReplicaVisibleLengthRequestProto)(nil),       // 0: hadoop.hdfs.GetReplicaVisibleLengthRequestProto
	(*GetReplicaVisibleLengthResponseProto)(nil),      // 1: hadoop.hdfs.GetReplicaVisibleLengthResponseProto
	(*RefreshNamenodesRequestProto)(nil),              // 2: hadoop.hdfs.RefreshNamenodesRequestProto
	(*RefreshNamenodesResponseProto)(nil),             // 3: hadoop.hdfs.RefreshNamenodesResponseProto
	(*DeleteBlockPoolRequestProto)(nil),               // 4: hadoop.hdfs.DeleteBlockPoolRequestProto
	(*DeleteBlockPoolResponseProto)(nil),              // 5: hadoop.hdfs.DeleteBlockPoolResponseProto
	(*GetBlockLocalPathInfoRequestProto)(nil),         // 6: hadoop.hdfs.GetBlockLocalPathInfoRequestProto
	(*GetBlockLocalPathInfoResponseProto)(nil),        // 7: hadoop.hdfs.GetBlockLocalPathInfoResponseProto
	(*ShutdownDatanodeRequestProto)(nil),              // 8: hadoop.hdfs.ShutdownDatanodeRequestProto
	(*ShutdownDatanodeResponseProto)(nil),             // 9: hadoop.hdfs.ShutdownDatanodeResponseProto
	(*EvictWritersRequestProto)(nil),                  // 10: hadoop.hdfs.EvictWritersRequestProto
	(*EvictWritersResponseProto)(nil),                 // 11: hadoop.hdfs.EvictWritersResponseProto
	(*GetDatanodeInfoRequestProto)(nil),               // 12: hadoop.hdfs.GetDatanodeInfoRequestProto
	(*GetDatanodeInfoResponseProto)(nil),              // 13: hadoop.hdfs.GetDatanodeInfoResponseProto
	(*TriggerBlockReportRequestProto)(nil),            // 14: hadoop.hdfs.TriggerBlockReportRequestProto
	(*TriggerBlockReportResponseProto)(nil),           // 15: hadoop.hdfs.TriggerBlockReportResponseProto
	(*GetBalancerBandwidthRequestProto)(nil),          // 16: hadoop.hdfs.GetBalancerBandwidthRequestProto
	(*GetBalancerBandwidthResponseProto)(nil),         // 17: hadoop.hdfs.GetBalancerBandwidthResponseProto
	(*ExtendedBlockProto)(nil),                        // 18: hadoop.hdfs.ExtendedBlockProto
	(*hadoop_common.TokenProto)(nil),                  // 19: hadoop.common.TokenProto
	(*DatanodeLocalInfoProto)(nil),                    // 20: hadoop.hdfs.DatanodeLocalInfoProto
	(*GetReconfigurationStatusRequestProto)(nil),      // 21: hadoop.hdfs.GetReconfigurationStatusRequestProto
	(*StartReconfigurationRequestProto)(nil),          // 22: hadoop.hdfs.StartReconfigurationRequestProto
	(*ListReconfigurablePropertiesRequestProto)(nil),  // 23: hadoop.hdfs.ListReconfigurablePropertiesRequestProto
	(*GetReconfigurationStatusResponseProto)(nil),     // 24: hadoop.hdfs.GetReconfigurationStatusResponseProto
	(*StartReconfigurationResponseProto)(nil),         // 25: hadoop.hdfs.StartReconfigurationResponseProto
	(*ListReconfigurablePropertiesResponseProto)(nil), // 26: hadoop.hdfs.ListReconfigurablePropertiesResponseProto
}
var file_ClientDatanodeProtocol_proto_depIdxs = []int32{
	18, // 0: hadoop.hdfs.GetReplicaVisibleLengthRequestProto.block:type_name -> hadoop.hdfs.ExtendedBlockProto
	18, // 1: hadoop.hdfs.GetBlockLocalPathInfoRequestProto.block:type_name -> hadoop.hdfs.ExtendedBlockProto
	19, // 2: hadoop.hdfs.GetBlockLocalPathInfoRequestProto.token:type_name -> hadoop.common.TokenProto
	18, // 3: hadoop.hdfs.GetBlockLocalPathInfoResponseProto.block:type_name -> hadoop.hdfs.ExtendedBlockProto
	20, // 4: hadoop.hdfs.GetDatanodeInfoResponseProto.localInfo:type_name -> hadoop.hdfs.DatanodeLocalInfoProto
	0,  // 5: hadoop.hdfs.ClientDatanodeProtocolService.getReplicaVisibleLength:input_type -> hadoop.hdfs.GetReplicaVisibleLengthRequestProto
	2,  // 6: hadoop.hdfs.ClientDatanodeProtocolService.refreshNamenodes:input_type -> hadoop.hdfs.RefreshNamenodesRequestProto
	4,  // 7: hadoop.hdfs.ClientDatanodeProtocolService.deleteBlockPool:input_type -> hadoop.hdfs.DeleteBlockPoolRequestProto
	6,  // 8: hadoop.hdfs.ClientDatanodeProtocolService.getBlockLocalPathInfo:input_type -> hadoop.hdfs.GetBlockLocalPathInfoRequestProto
	8,  // 9: hadoop.hdfs.ClientDatanodeProtocolService.shutdownDatanode:input_type -> hadoop.hdfs.ShutdownDatanodeRequestProto
	10, // 10: hadoop.hdfs.ClientDatanodeProtocolService.evictWriters:input_type -> hadoop.hdfs.EvictWritersRequestProto
	12, // 11: hadoop.hdfs.ClientDatanodeProtocolService.getDatanodeInfo:input_type -> hadoop.hdfs.GetDatanodeInfoRequestProto
	21, // 12: hadoop.hdfs.ClientDatanodeProtocolService.getReconfigurationStatus:input_type -> hadoop.hdfs.GetReconfigurationStatusRequestProto
	22, // 13: hadoop.hdfs.ClientDatanodeProtocolService.startReconfiguration:input_type -> hadoop.hdfs.StartReconfigurationRequestProto
	23, // 14: hadoop.hdfs.ClientDatanodeProtocolService.listReconfigurableProperties:input_type -> hadoop.hdfs.ListReconfigurablePropertiesRequestProto
	14, // 15: hadoop.hdfs.ClientDatanodeProtocolService.triggerBlockReport:input_type -> hadoop.hdfs.TriggerBlockReportRequestProto
	16, // 16: hadoop.hdfs.ClientDatanodeProtocolService.getBalancerBandwidth:input_type -> hadoop.hdfs.GetBalancerBandwidthRequestProto
	1,  // 17: hadoop.hdfs.ClientDatanodeProtocolService.getReplicaVisibleLength:output_type -> hadoop.hdfs.GetReplicaVisibleLengthResponseProto
	3,  // 18: hadoop.hdfs.ClientDatanodeProtocolService.refreshNamenodes:output_type -> hadoop.hdfs.RefreshNamenodesResponseProto
	5,  // 19: hadoop.hdfs.ClientDatanodeProtocolService.deleteBlockPool:output_type -> hadoop.hdfs.DeleteBlockPoolResponseProto
	7,  // 20: hadoop.hdfs.ClientDatanodeProtocolService.getBlockLocalPathInfo:output_type -> hadoop.hdfs.GetBlockLocalPathInfoResponseProto
	9,  // 21: hadoop.hdfs.ClientDatanodeProtocolService.shutdownDatanode:output_type -> hadoop.hdfs.ShutdownDatanodeResponseProto
	11, // 22: hadoop.hdfs.ClientDatanodeProtocolService.evictWriters:output_type -> hadoop.hdfs.EvictWritersResponseProto
	13, // 23: hadoop.hdfs.ClientDatanodeProtocolService.getDatanodeInfo:output_type -> hadoop.hdfs.GetDatanodeInfoResponseProto
	24, // 24: hadoop.hdfs.ClientDatanodeProtocolService.getReconfigurationStatus:output_type -> hadoop.hdfs.GetReconfigurationStatusResponseProto
	25, // 25: hadoop.hdfs.ClientDatanodeProtocolService.startReconfiguration:output_type -> hadoop.hdfs.StartReconfigurationResponseProto
	26, // 26: hadoop.hdfs.ClientDatanodeProtocolService.listReconfigurableProperties:output_type -> hadoop.hdfs.ListReconfigurablePropertiesResponseProto
	15, // 27: hadoop.hdfs.ClientDatanodeProtocolService.triggerBlockReport:output_type -> hadoop.hdfs.TriggerBlockReportResponseProto
	17, // 28: hadoop.hdfs.ClientDatanodeProtocolService.getBalancerBandwidth:output_type -> hadoop.hdfs.GetBalancerBandwidthResponseProto
	17, // [17:29] is the sub-list for method output_type
	5,  // [5:17] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_ClientDatanodeProtocol_proto_init() }
func file_ClientDatanodeProtocol_proto_init() {
	if File_ClientDatanodeProtocol_proto != nil {
		return
	}
	file_hdfs_proto_init()
	file_ReconfigurationProtocol_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ClientDatanodeProtocol_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReplicaVisibleLengthRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ClientDatanodeProtocol_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReplicaVisibleLengthResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ClientDatanodeProtocol_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshNamenodesRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ClientDatanodeProtocol_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshNamenodesResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ClientDatanodeProtocol_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBlockPoolRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ClientDatanodeProtocol_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBlockPoolResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ClientDatanodeProtocol_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlockLocalPathInfoRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ClientDatanodeProtocol_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlockLocalPathInfoResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ClientDatanodeProtocol_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShutdownDatanodeRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ClientDatanodeProtocol_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShutdownDatanodeResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ClientDatanodeProtocol_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvictWritersRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ClientDatanodeProtocol_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvictWritersResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ClientDatanodeProtocol_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDatanodeInfoRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ClientDatanodeProtocol_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDatanodeInfoResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ClientDatanodeProtocol_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TriggerBlockReportRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ClientDatanodeProtocol_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TriggerBlockReportResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ClientDatanodeProtocol_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBalancerBandwidthRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ClientDatanodeProtocol_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBalancerBandwidthResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ClientDatanodeProtocol_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ClientDatanodeProtocol_proto_goTypes,
		DependencyIndexes: file_ClientDatanodeProtocol_proto_depIdxs,
		MessageInfos:      file_ClientDatanodeProtocol_proto_msgTypes,
	}.Build()
	File_ClientDatanodeProtocol_proto = out.File
	file_ClientDatanodeProtocol_proto_rawDesc = nil
	file_ClientDatanodeProtocol_proto_goTypes = nil
	file_ClientDatanodeProtocol_proto_depIdxs = nil
}
