// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: erasurecoding.proto

package hadoop_hdfs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetErasureCodingPolicyRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Src      *string                   `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	EcPolicy *ErasureCodingPolicyProto `protobuf:"bytes,2,opt,name=ecPolicy" json:"ecPolicy,omitempty"`
}

func (x *SetErasureCodingPolicyRequestProto) Reset() {
	*x = SetErasureCodingPolicyRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_erasurecoding_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetErasureCodingPolicyRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetErasureCodingPolicyRequestProto) ProtoMessage() {}

func (x *SetErasureCodingPolicyRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_erasurecoding_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetErasureCodingPolicyRequestProto.ProtoReflect.Descriptor instead.
func (*SetErasureCodingPolicyRequestProto) Descriptor() ([]byte, []int) {
	return file_erasurecoding_proto_rawDescGZIP(), []int{0}
}

func (x *SetErasureCodingPolicyRequestProto) GetSrc() string {
	if x != nil && x.Src != nil {
		return *x.Src
	}
	return ""
}

func (x *SetErasureCodingPolicyRequestProto) GetEcPolicy() *ErasureCodingPolicyProto {
	if x != nil {
		return x.EcPolicy
	}
	return nil
}

type SetErasureCodingPolicyResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetErasureCodingPolicyResponseProto) Reset() {
	*x = SetErasureCodingPolicyResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_erasurecoding_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetErasureCodingPolicyResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetErasureCodingPolicyResponseProto) ProtoMessage() {}

func (x *SetErasureCodingPolicyResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_erasurecoding_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetErasureCodingPolicyResponseProto.ProtoReflect.Descriptor instead.
func (*SetErasureCodingPolicyResponseProto) Descriptor() ([]byte, []int) {
	return file_erasurecoding_proto_rawDescGZIP(), []int{1}
}

type GetErasureCodingPoliciesRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetErasureCodingPoliciesRequestProto) Reset() {
	*x = GetErasureCodingPoliciesRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_erasurecoding_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetErasureCodingPoliciesRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetErasureCodingPoliciesRequestProto) ProtoMessage() {}

func (x *GetErasureCodingPoliciesRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_erasurecoding_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetErasureCodingPoliciesRequestProto.ProtoReflect.Descriptor instead.
func (*GetErasureCodingPoliciesRequestProto) Descriptor() ([]byte, []int) {
	return file_erasurecoding_proto_rawDescGZIP(), []int{2}
}

type GetErasureCodingPoliciesResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EcPolicies []*ErasureCodingPolicyProto `protobuf:"bytes,1,rep,name=ecPolicies" json:"ecPolicies,omitempty"`
}

func (x *GetErasureCodingPoliciesResponseProto) Reset() {
	*x = GetErasureCodingPoliciesResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_erasurecoding_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetErasureCodingPoliciesResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetErasureCodingPoliciesResponseProto) ProtoMessage() {}

func (x *GetErasureCodingPoliciesResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_erasurecoding_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetErasureCodingPoliciesResponseProto.ProtoReflect.Descriptor instead.
func (*GetErasureCodingPoliciesResponseProto) Descriptor() ([]byte, []int) {
	return file_erasurecoding_proto_rawDescGZIP(), []int{3}
}

func (x *GetErasureCodingPoliciesResponseProto) GetEcPolicies() []*ErasureCodingPolicyProto {
	if x != nil {
		return x.EcPolicies
	}
	return nil
}

type GetErasureCodingPolicyRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Src *string `protobuf:"bytes,1,req,name=src" json:"src,omitempty"` // path to get the policy info
}

func (x *GetErasureCodingPolicyRequestProto) Reset() {
	*x = GetErasureCodingPolicyRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_erasurecoding_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetErasureCodingPolicyRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetErasureCodingPolicyRequestProto) ProtoMessage() {}

func (x *GetErasureCodingPolicyRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_erasurecoding_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetErasureCodingPolicyRequestProto.ProtoReflect.Descriptor instead.
func (*GetErasureCodingPolicyRequestProto) Descriptor() ([]byte, []int) {
	return file_erasurecoding_proto_rawDescGZIP(), []int{4}
}

func (x *GetErasureCodingPolicyRequestProto) GetSrc() string {
	if x != nil && x.Src != nil {
		return *x.Src
	}
	return ""
}

type GetErasureCodingPolicyResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EcPolicy *ErasureCodingPolicyProto `protobuf:"bytes,1,opt,name=ecPolicy" json:"ecPolicy,omitempty"`
}

func (x *GetErasureCodingPolicyResponseProto) Reset() {
	*x = GetErasureCodingPolicyResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_erasurecoding_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetErasureCodingPolicyResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetErasureCodingPolicyResponseProto) ProtoMessage() {}

func (x *GetErasureCodingPolicyResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_erasurecoding_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetErasureCodingPolicyResponseProto.ProtoReflect.Descriptor instead.
func (*GetErasureCodingPolicyResponseProto) Descriptor() ([]byte, []int) {
	return file_erasurecoding_proto_rawDescGZIP(), []int{5}
}

func (x *GetErasureCodingPolicyResponseProto) GetEcPolicy() *ErasureCodingPolicyProto {
	if x != nil {
		return x.EcPolicy
	}
	return nil
}

//*
// Block erasure coding reconstruction info
type BlockECReconstructionInfoProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Block              *ExtendedBlockProto       `protobuf:"bytes,1,req,name=block" json:"block,omitempty"`
	SourceDnInfos      *DatanodeInfosProto       `protobuf:"bytes,2,req,name=sourceDnInfos" json:"sourceDnInfos,omitempty"`
	TargetDnInfos      *DatanodeInfosProto       `protobuf:"bytes,3,req,name=targetDnInfos" json:"targetDnInfos,omitempty"`
	TargetStorageUuids *StorageUuidsProto        `protobuf:"bytes,4,req,name=targetStorageUuids" json:"targetStorageUuids,omitempty"`
	TargetStorageTypes *StorageTypesProto        `protobuf:"bytes,5,req,name=targetStorageTypes" json:"targetStorageTypes,omitempty"`
	LiveBlockIndices   []byte                    `protobuf:"bytes,6,req,name=liveBlockIndices" json:"liveBlockIndices,omitempty"`
	EcPolicy           *ErasureCodingPolicyProto `protobuf:"bytes,7,req,name=ecPolicy" json:"ecPolicy,omitempty"`
}

func (x *BlockECReconstructionInfoProto) Reset() {
	*x = BlockECReconstructionInfoProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_erasurecoding_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockECReconstructionInfoProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockECReconstructionInfoProto) ProtoMessage() {}

func (x *BlockECReconstructionInfoProto) ProtoReflect() protoreflect.Message {
	mi := &file_erasurecoding_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockECReconstructionInfoProto.ProtoReflect.Descriptor instead.
func (*BlockECReconstructionInfoProto) Descriptor() ([]byte, []int) {
	return file_erasurecoding_proto_rawDescGZIP(), []int{6}
}

func (x *BlockECReconstructionInfoProto) GetBlock() *ExtendedBlockProto {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *BlockECReconstructionInfoProto) GetSourceDnInfos() *DatanodeInfosProto {
	if x != nil {
		return x.SourceDnInfos
	}
	return nil
}

func (x *BlockECReconstructionInfoProto) GetTargetDnInfos() *DatanodeInfosProto {
	if x != nil {
		return x.TargetDnInfos
	}
	return nil
}

func (x *BlockECReconstructionInfoProto) GetTargetStorageUuids() *StorageUuidsProto {
	if x != nil {
		return x.TargetStorageUuids
	}
	return nil
}

func (x *BlockECReconstructionInfoProto) GetTargetStorageTypes() *StorageTypesProto {
	if x != nil {
		return x.TargetStorageTypes
	}
	return nil
}

func (x *BlockECReconstructionInfoProto) GetLiveBlockIndices() []byte {
	if x != nil {
		return x.LiveBlockIndices
	}
	return nil
}

func (x *BlockECReconstructionInfoProto) GetEcPolicy() *ErasureCodingPolicyProto {
	if x != nil {
		return x.EcPolicy
	}
	return nil
}

var File_erasurecoding_proto protoreflect.FileDescriptor

var file_erasurecoding_proto_rawDesc = []byte{
	0x0a, 0x13, 0x65, 0x72, 0x61, 0x73, 0x75, 0x72, 0x65, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x64,
	0x66, 0x73, 0x1a, 0x0a, 0x68, 0x64, 0x66, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6a,
	0x0a, 0x22, 0x53, 0x65, 0x74, 0x45, 0x72, 0x61, 0x73, 0x75, 0x72, 0x65, 0x43, 0x6f, 0x64, 0x69,
	0x6e, 0x67, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x09, 0x12, 0x37, 0x0a, 0x08, 0x65, 0x63, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x64, 0x66,
	0x73, 0x2e, 0x45, 0x72, 0x61, 0x73, 0x75, 0x72, 0x65, 0x43, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x50,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x25, 0x0a, 0x23, 0x53, 0x65,
	0x74, 0x45, 0x72, 0x61, 0x73, 0x75, 0x72, 0x65, 0x43, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x26, 0x0a, 0x24, 0x47, 0x65, 0x74, 0x45, 0x72, 0x61, 0x73, 0x75, 0x72, 0x65, 0x43,
	0x6f, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x62, 0x0a, 0x25, 0x47, 0x65, 0x74,
	0x45, 0x72, 0x61, 0x73, 0x75, 0x72, 0x65, 0x43, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x6c,
	0x69, 0x63, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x39, 0x0a, 0x0a, 0x65, 0x63, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e,
	0x68, 0x64, 0x66, 0x73, 0x2e, 0x45, 0x72, 0x61, 0x73, 0x75, 0x72, 0x65, 0x43, 0x6f, 0x64, 0x69,
	0x6e, 0x67, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a,
	0x22, 0x47, 0x65, 0x74, 0x45, 0x72, 0x61, 0x73, 0x75, 0x72, 0x65, 0x43, 0x6f, 0x64, 0x69, 0x6e,
	0x67, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09,
	0x22, 0x5e, 0x0a, 0x23, 0x47, 0x65, 0x74, 0x45, 0x72, 0x61, 0x73, 0x75, 0x72, 0x65, 0x43, 0x6f,
	0x64, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x37, 0x0a, 0x08, 0x65, 0x63, 0x50, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x68, 0x61, 0x64, 0x6f,
	0x6f, 0x70, 0x2e, 0x68, 0x64, 0x66, 0x73, 0x2e, 0x45, 0x72, 0x61, 0x73, 0x75, 0x72, 0x65, 0x43,
	0x6f, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x8b, 0x03, 0x0a, 0x1e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x45, 0x43, 0x52, 0x65, 0x63, 0x6f,
	0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x2e, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x64, 0x66, 0x73,
	0x2e, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x36, 0x0a, 0x0d, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x44, 0x6e, 0x49,
	0x6e, 0x66, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x68, 0x61, 0x64,
	0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x64, 0x66, 0x73, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x36, 0x0a, 0x0d, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x44, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x02,
	0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x64, 0x66, 0x73,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x3a, 0x0a, 0x12, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x53, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x55, 0x75, 0x69, 0x64, 0x73, 0x18, 0x04, 0x20, 0x02, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x64, 0x66, 0x73, 0x2e, 0x53, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x55, 0x75, 0x69, 0x64, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x3a, 0x0a, 0x12, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x73, 0x18, 0x05, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x68, 0x61,
	0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x64, 0x66, 0x73, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x0a, 0x10, 0x6c,
	0x69, 0x76, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x18,
	0x06, 0x20, 0x02, 0x28, 0x0c, 0x12, 0x37, 0x0a, 0x08, 0x65, 0x63, 0x50, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x18, 0x07, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70,
	0x2e, 0x68, 0x64, 0x66, 0x73, 0x2e, 0x45, 0x72, 0x61, 0x73, 0x75, 0x72, 0x65, 0x43, 0x6f, 0x64,
	0x69, 0x6e, 0x67, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x82,
	0x01, 0x0a, 0x25, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x70, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x68, 0x61,
	0x64, 0x6f, 0x6f, 0x70, 0x2e, 0x68, 0x64, 0x66, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x13, 0x45, 0x72, 0x61, 0x73, 0x75, 0x72,
	0x65, 0x43, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x5a, 0x41, 0x68,
	0x74, 0x74, 0x70, 0x3a, 0x2f, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x63, 0x6f, 0x6c, 0x69, 0x6e, 0x6d, 0x61, 0x72, 0x63, 0x2f, 0x68, 0x64, 0x66, 0x73, 0x2f,
	0x76, 0x32, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x68, 0x61, 0x64, 0x6f, 0x6f, 0x70, 0x5f, 0x68, 0x64, 0x66, 0x73,
	0xa0, 0x01, 0x01,
}

var (
	file_erasurecoding_proto_rawDescOnce sync.Once
	file_erasurecoding_proto_rawDescData = file_erasurecoding_proto_rawDesc
)

func file_erasurecoding_proto_rawDescGZIP() []byte {
	file_erasurecoding_proto_rawDescOnce.Do(func() {
		file_erasurecoding_proto_rawDescData = protoimpl.X.CompressGZIP(file_erasurecoding_proto_rawDescData)
	})
	return file_erasurecoding_proto_rawDescData
}

var file_erasurecoding_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_erasurecoding_proto_goTypes = []interface{}{
	(*SetErasureCodingPolicyRequestProto)(nil),    // 0: hadoop.hdfs.SetErasureCodingPolicyRequestProto
	(*SetErasureCodingPolicyResponseProto)(nil),   // 1: hadoop.hdfs.SetErasureCodingPolicyResponseProto
	(*GetErasureCodingPoliciesRequestProto)(nil),  // 2: hadoop.hdfs.GetErasureCodingPoliciesRequestProto
	(*GetErasureCodingPoliciesResponseProto)(nil), // 3: hadoop.hdfs.GetErasureCodingPoliciesResponseProto
	(*GetErasureCodingPolicyRequestProto)(nil),    // 4: hadoop.hdfs.GetErasureCodingPolicyRequestProto
	(*GetErasureCodingPolicyResponseProto)(nil),   // 5: hadoop.hdfs.GetErasureCodingPolicyResponseProto
	(*BlockECReconstructionInfoProto)(nil),        // 6: hadoop.hdfs.BlockECReconstructionInfoProto
	(*ErasureCodingPolicyProto)(nil),              // 7: hadoop.hdfs.ErasureCodingPolicyProto
	(*ExtendedBlockProto)(nil),                    // 8: hadoop.hdfs.ExtendedBlockProto
	(*DatanodeInfosProto)(nil),                    // 9: hadoop.hdfs.DatanodeInfosProto
	(*StorageUuidsProto)(nil),                     // 10: hadoop.hdfs.StorageUuidsProto
	(*StorageTypesProto)(nil),                     // 11: hadoop.hdfs.StorageTypesProto
}
var file_erasurecoding_proto_depIdxs = []int32{
	7,  // 0: hadoop.hdfs.SetErasureCodingPolicyRequestProto.ecPolicy:type_name -> hadoop.hdfs.ErasureCodingPolicyProto
	7,  // 1: hadoop.hdfs.GetErasureCodingPoliciesResponseProto.ecPolicies:type_name -> hadoop.hdfs.ErasureCodingPolicyProto
	7,  // 2: hadoop.hdfs.GetErasureCodingPolicyResponseProto.ecPolicy:type_name -> hadoop.hdfs.ErasureCodingPolicyProto
	8,  // 3: hadoop.hdfs.BlockECReconstructionInfoProto.block:type_name -> hadoop.hdfs.ExtendedBlockProto
	9,  // 4: hadoop.hdfs.BlockECReconstructionInfoProto.sourceDnInfos:type_name -> hadoop.hdfs.DatanodeInfosProto
	9,  // 5: hadoop.hdfs.BlockECReconstructionInfoProto.targetDnInfos:type_name -> hadoop.hdfs.DatanodeInfosProto
	10, // 6: hadoop.hdfs.BlockECReconstructionInfoProto.targetStorageUuids:type_name -> hadoop.hdfs.StorageUuidsProto
	11, // 7: hadoop.hdfs.BlockECReconstructionInfoProto.targetStorageTypes:type_name -> hadoop.hdfs.StorageTypesProto
	7,  // 8: hadoop.hdfs.BlockECReconstructionInfoProto.ecPolicy:type_name -> hadoop.hdfs.ErasureCodingPolicyProto
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_erasurecoding_proto_init() }
func file_erasurecoding_proto_init() {
	if File_erasurecoding_proto != nil {
		return
	}
	file_hdfs_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_erasurecoding_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetErasureCodingPolicyRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_erasurecoding_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetErasureCodingPolicyResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_erasurecoding_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetErasureCodingPoliciesRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_erasurecoding_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetErasureCodingPoliciesResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_erasurecoding_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetErasureCodingPolicyRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_erasurecoding_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetErasureCodingPolicyResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_erasurecoding_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockECReconstructionInfoProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_erasurecoding_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_erasurecoding_proto_goTypes,
		DependencyIndexes: file_erasurecoding_proto_depIdxs,
		MessageInfos:      file_erasurecoding_proto_msgTypes,
	}.Build()
	File_erasurecoding_proto = out.File
	file_erasurecoding_proto_rawDesc = nil
	file_erasurecoding_proto_goTypes = nil
	file_erasurecoding_proto_depIdxs = nil
}
